blank_issues_enabled: true
contact_links:
  - name: biblio Core Security Policy
    url: https://github.com/bitcoin/bitcoin/blob/master/SECURITY.md
    about: View security policy
  - name: biblio Core Developers
    url: https://bitcoincore.org
    about: biblio Core homepage
